### ISSUE TITLE
Why can't docker images be managed via Powershell ISE?

### ISSUE THREAD

**Issue by mathiasconradt** [Microsoft/Virtualization-Documentation#156] opened 2016-03-03 09:17 UTC
It's not clear why Docker commands cannot be managed via Powershell ISE but only in Powershell, while Windows containers can and should be mentioned on https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker.

With "manage" I mean "docker attach" and "Enter-PSSession", attaching to a container session.

I get these errors when trying to attach to a docker container via Powershell ISE: http://snag.gy/EehYI.jpg

**Comment by StefanScherer** [comment] 2016-03-04 20:13
The error shows something with docker/pkg/term/windows/ansi_reader.go - perhaps a problem with the different kind of terminal in ISE instead of vanilla PowerShell?
Seems to me like an error in docker.exe client.

**Comment by PatrickLang** [comment] 2016-03-21 16:19
Thanks for bringing this up. Can you open an issue on the main Docker project for this? We should discuss the impact & workarounds there with the larger community there. 
https://github.com/docker/docker/issues/

**Comment by mathiasconradt** [comment] 2016-03-21 16:34
@PatrickLang Ticket opened here: https://github.com/docker/docker/issues/21368

**Comment by neilpeterson** [comment] 2016-05-23 18:14
Closing this, the issue is being tracked on the Docker project.

**Closed by neilpeterson** 2016-05-23 18:14 UTC
