### ISSUE TITLE
 No Command  `Install-ContainerHost.ps1` on Windows 10 build 10586 

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/Virtualization-Documentation#106] opened 2015-12-21 03:18 UTC
On my  Windows 10 build 10586 , “Get-ContainerImage” is not exist.
So `Install-ContainerHost.ps1` failed.
https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/inplace_setup.md

**Comment by qin-nz** [comment] 2015-12-21 03:20
My Windows 10 is Professional Edition

**Comment by neilpeterson** [comment] 2015-12-21 05:46
Qin-nz, you will need to use Hyper-V on Windows 10 for the container host. This doc details a scripted deployment, which will work on Windows 10 - https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/container_setup .

Let me know if this resolves our issue.

Thanks

neilp

**Comment by qin-nz** [comment] 2015-12-24 09:32
Is it means my `Windows 10` need a `Windows Server 2016` Virtual Machine, and run docker on `Windows Server 2016` ?

**Comment by neilpeterson** [comment] 2015-12-24 20:01
Yes this is correct. The container role can only be enabled on a Windows Server 2016 TP4 installation.

**Comment by scooley** [comment] 2016-01-04 22:01
Closing this issue -- good feedback but not a bug.

**Closed by scooley** 2016-01-04 22:01 UTC

**Comment by neilpeterson** [comment] 2016-01-04 22:33
I've updated the doc's to be more clear around this topic.
